package de.uniwue.info6.database.map;

// Generated Oct 30, 2013 2:01:27 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * ExerciseGroup generated by hbm2java
 */
public class ExerciseGroup implements java.io.Serializable {

	// ******************************************************************
	// custom (not generated methods)
	// ******************************************************************
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof ExerciseGroup)) {
			return false;
		}
		ExerciseGroup other = (ExerciseGroup) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}
	
	// ******************************************************************
	// generated methods of hibernate
	// ******************************************************************

	private Integer id;
	private Scenario scenario;
	private ExerciseGroup exerciseGroup;
	private String name;
	private String description;
	private Date lastModified;
	private Date startTime;
	private Date endTime;
	private Boolean isRated;
	private Set exercises = new HashSet(0);
	private Set exerciseGroups = new HashSet(0);

	public ExerciseGroup() {
	}

	public ExerciseGroup(String name, Date lastModified, Date startTime, Date endTime) {
		this.name = name;
		this.lastModified = lastModified;
		this.startTime = startTime;
		this.endTime = endTime;
	}

	public ExerciseGroup(Scenario scenario, ExerciseGroup exerciseGroup, String name, String description,
			Date lastModified, Date startTime, Date endTime, Boolean isRated, Set exercises, Set exerciseGroups) {
		this.scenario = scenario;
		this.exerciseGroup = exerciseGroup;
		this.name = name;
		this.description = description;
		this.lastModified = lastModified;
		this.startTime = startTime;
		this.endTime = endTime;
		this.isRated = isRated;
		this.exercises = exercises;
		this.exerciseGroups = exerciseGroups;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Scenario getScenario() {
		return this.scenario;
	}

	@XmlTransient
	public void setScenario(Scenario scenario) {
		this.scenario = scenario;
	}

	public ExerciseGroup getExerciseGroup() {
		return this.exerciseGroup;
	}

	@XmlTransient
	public void setExerciseGroup(ExerciseGroup exerciseGroup) {
		this.exerciseGroup = exerciseGroup;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public Boolean getIsRated() {
		return this.isRated;
	}

	public void setIsRated(Boolean isRated) {
		this.isRated = isRated;
	}

	public Set getExercises() {
		return this.exercises;
	}

 	@XmlElement(name="exercise", type=Exercise.class)
	public void setExercises(Set exercises) {
		this.exercises = exercises;
	}

	public Set getExerciseGroups() {
		return this.exerciseGroups;
	}

	@XmlTransient
	public void setExerciseGroups(Set exerciseGroups) {
		this.exerciseGroups = exerciseGroups;
	}

}
