package de.uniwue.info6.database.map;

// Generated Oct 30, 2013 2:01:27 PM by Hibernate Tools 4.0.0

/**
 * UserRight generated by hbm2java
 */
public class UserRight implements java.io.Serializable {
	// ******************************************************************
	// custom (not generated methods)
	// ******************************************************************
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((scenario == null) ? 0 : scenario.hashCode());
		result = prime * result + ((user == null) ? 0 : user.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof UserRight)) {
			return false;
		}
		UserRight other = (UserRight) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		if (scenario == null) {
			if (other.scenario != null) {
				return false;
			}
		} else if (!scenario.equals(other.scenario)) {
			return false;
		}
		if (user == null) {
			if (other.user != null) {
				return false;
			}
		} else if (!user.equals(other.user)) {
			return false;
		}
		return true;
	}
	// ******************************************************************
	// generated methods of hibernate
	// ******************************************************************


	private Integer id;
	private User user;
	private Scenario scenario;
	private Boolean hasRatingRights;
	private Boolean hasEditingRights;

	public UserRight() {
	}

	public UserRight(User user) {
		this.user = user;
	}

	public UserRight(User user, Scenario scenario, Boolean hasRatingRights, Boolean hasEditingRights) {
		this.user = user;
		this.scenario = scenario;
		this.hasRatingRights = hasRatingRights;
		this.hasEditingRights = hasEditingRights;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Scenario getScenario() {
		return this.scenario;
	}

	public void setScenario(Scenario scenario) {
		this.scenario = scenario;
	}

	public Boolean getHasRatingRights() {
		return this.hasRatingRights;
	}

	public void setHasRatingRights(Boolean hasRatingRights) {
		this.hasRatingRights = hasRatingRights;
	}

	public Boolean getHasEditingRights() {
		return this.hasEditingRights;
	}

	public void setHasEditingRights(Boolean hasEditingRights) {
		this.hasEditingRights = hasEditingRights;
	}

}
