package de.uniwue.info6.database.map;

// Generated Oct 30, 2013 2:01:27 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {
	// ******************************************************************
	// custom (not generated methods)
	// ******************************************************************

	@Override
	public int hashCode() {
		return new HashCodeBuilder(17, 31).append(id).toHashCode();
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null)
			return false;
		if (obj == this)
			return true;
		if (!(obj instanceof User))
			return false;

		User user = (User) obj;
		return new EqualsBuilder().append(id, user.getId()).isEquals();
	}

	// ******************************************************************
	// generated methods of hibernate
	// ******************************************************************

	private String id;
	private Date lastModified;
	private Boolean isAdmin;
	private String description;
	private Set userEntries = new HashSet(0);
	private Set userResults = new HashSet(0);
	private Set userExTags = new HashSet(0);
	private Set userRights = new HashSet(0);

	public User() {
	}

	public User(String id, Date lastModified) {
		this.id = id;
		this.lastModified = lastModified;
	}

	public User(String id, Date lastModified, Boolean isAdmin, String description, Set userEntries, Set userResults,
			Set userExTags, Set userRights) {
		this.id = id;
		this.lastModified = lastModified;
		this.isAdmin = isAdmin;
		this.description = description;
		this.userEntries = userEntries;
		this.userResults = userResults;
		this.userExTags = userExTags;
		this.userRights = userRights;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

	public Boolean getIsAdmin() {
		return this.isAdmin;
	}

	public void setIsAdmin(Boolean isAdmin) {
		this.isAdmin = isAdmin;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getUserEntries() {
		return this.userEntries;
	}

	public void setUserEntries(Set userEntries) {
		this.userEntries = userEntries;
	}

	public Set getUserResults() {
		return this.userResults;
	}

	public void setUserResults(Set userResults) {
		this.userResults = userResults;
	}

	public Set getUserExTags() {
		return this.userExTags;
	}

	public void setUserExTags(Set userExTags) {
		this.userExTags = userExTags;
	}

	public Set getUserRights() {
		return this.userRights;
	}

	public void setUserRights(Set userRights) {
		this.userRights = userRights;
	}

}
