package de.uniwue.info6.database.map;

import de.uniwue.info6.database.map.daos.UserRightDao;

/*
 * #%L
 * ************************************************************************
 * ORGANIZATION  :  Institute of Computer Science, University of Wuerzburg
 * PROJECT       :  UEPS - Uebungs-Programm fuer SQL
 * FILENAME      :  UserRight.java
 * ************************************************************************
 * %%
 * Copyright (C) 2014 - 2015 Institute of Computer Science, University of Wuerzburg
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

// Generated Oct 30, 2013 2:01:27 PM by Hibernate Tools 4.0.0

/**
 * UserRight generated by hbm2java
 */
public class UserRight implements java.io.Serializable {
  // ******************************************************************
  // custom (not generated methods)
  // ******************************************************************

  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((id == null) ? 0 : id.hashCode());
    result = prime * result + ((scenario == null) ? 0 : scenario.hashCode());
    result = prime * result + ((user == null) ? 0 : user.hashCode());
    return result;
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (obj == null) {
      return false;
    }
    if (!(obj instanceof UserRight)) {
      return false;
    }
    UserRight other = (UserRight) obj;
    if (id == null) {
      if (other.id != null) {
        return false;
      }
    } else if (!id.equals(other.id)) {
      return false;
    }
    if (scenario == null) {
      if (other.scenario != null) {
        return false;
      }
    } else if (!scenario.equals(other.scenario)) {
      return false;
    }
    if (user == null) {
      if (other.user != null) {
        return false;
      }
    } else if (!user.equals(other.user)) {
      return false;
    }
    return true;
  }
  // ******************************************************************
  // generated methods of hibernate
  // ******************************************************************


  private Integer id;
  private User user;
  private User createdByUser;
  private Scenario scenario;
  private Boolean hasRatingRights;
  private Boolean hasGroupEditingRights;
  private Boolean hasScenarioEditingRights;

  public UserRight() {
  }

  public UserRight(User user) {
    this.user = user;
  }

  public UserRight(User user, User createdByUser, Scenario scenario, Boolean hasRatingRights, Boolean hasGroupEditingRights,
                   Boolean hasScenarioEditingRights) {
    this.user = user;
    this.createdByUser = createdByUser;
    this.scenario = scenario;
    this.hasRatingRights = hasRatingRights;
    this.hasGroupEditingRights = hasGroupEditingRights;
    this.hasScenarioEditingRights = hasScenarioEditingRights;
  }

  public Integer getId() {
    return this.id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public User getUser() {
    return this.user;
  }

  public void setUser(User user) {
    this.user = user;
  }

  public User getCreatedByUser() {
    return this.createdByUser;
  }

  public void setCreatedByUser(User createdByUser) {
    this.createdByUser = createdByUser;
  }

  public Scenario getScenario() {
    return this.scenario;
  }

  public void setScenario(Scenario scenario) {
    this.scenario = scenario;
  }

  public Boolean getHasRatingRights() {
    return this.hasRatingRights;
  }

  public void setHasRatingRights(Boolean hasRatingRights) {
    this.hasRatingRights = hasRatingRights;
  }

  public Boolean getHasGroupEditingRights() {
    return this.hasGroupEditingRights;
  }

  public void setHasGroupEditingRights(Boolean hasGroupEditingRights) {
    this.hasGroupEditingRights = hasGroupEditingRights;
  }

  public Boolean getHasScenarioEditingRights() {
    return this.hasScenarioEditingRights;
  }

  public void setHasScenarioEditingRights(Boolean hasScenarioEditingRights) {
    this.hasScenarioEditingRights = hasScenarioEditingRights;
  }

  public UserRight pull() {
    return new UserRightDao().getById(getId());
  }
}
