package de.uniwue.info6.misc.properties;

public enum PropString {
  ADMINS,
  SCENARIO_RESOURCES_PATH,
  SECRET_ID_STRING,

  FALLBACK_USER,
  FALLBACK_SECUREVALUE,
  FALLBACK_SCENARIO,

  MASTER_DBHOST,
  MASTER_DBPORT,
  MASTER_DBNAME,
  MASTER_DBUSER,
  MASTER_DBPASS,

  MOODLE_URL,
  LOG_PATH
}
