package de.uniwue.info6.misc.properties;

public enum PropBool {
  SHOW_SOL_TO_PRIVELEGED,
  IMPORT_DB_IF_EMPTY,
  IMPORT_EXAMPLE_SCENARIO,
  FORCE_RESET_DATABASE,
  USE_MOODLE_LOGIN,
  USE_FALLBACK_USER,
  LOG_BROWSER_HISTORY,
  ONLY_SAVE_LAST_USER_QUERY,
  DEBUG_MODE,
  LOG_PERFORMANCE
}
