package de.uniwue.info6.misc.properties;

public enum PropString {
  // @formatter:off
  ADMINS,
  SCENARIO_RESOURCES,
  SECRET_ID_STRING,

  USE_FALLBACK_USER,
  FALLBACK_USER,
  FALLBACK_SECUREVALUE,

  MAIN_DBHOST,
  MAIN_DBPORT,
  MAIN_DBNAME,
  MAIN_DBUSER,
  MAIN_DBPASS,

  EXAMPLE_SCENARIO_DBHOST,
  EXAMPLE_SCENARIO_DBPORT,
  EXAMPLE_SCENARIO_DBNAME,
  EXAMPLE_SCENARIO_DBUSER,
  EXAMPLE_SCENARIO_DBPASS,
  // @formatter:on
  ;
}
